apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "speedtest-exporter.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "speedtest-exporter.labels" . | nindent 4 }}
data:
  config.yaml: {{ .Values.config | toYaml | quote }}
