---
name: "Renovate"

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "dry-run"
        default: "false"
        required: false
      log-level:
        description: "log-level"
        default: debug
        required: false
  schedule:
    - cron: "10 * 1 * *"
  push:
    branches: ["main"]
    paths:
      - .github/renovate-bot.json5
      - .github/renovate.json5

jobs:
  renovate:
    uses: heathcliff26/ci/.github/workflows/renovate.yaml@main
    permissions: {}
    with:
      dry-run: ${{ github.event.inputs.dry-run || false }}
      log-level: "${{ github.event.inputs.log-level || 'debug' }}"
    secrets: inherit
